import type { CommandResult } from "./types.js";

export const experience = (): CommandResult => ({
  lines: [
    { text: "── Experience ────────────────────────────", tone: "section" },
    { text: "" },
    { text: "Back-End Developer", tone: "accent indent" },
    { text: "Storebrand · 05/2025–Present · Oslo", tone: "indent" },
    { text: "" },
    { text: "─────────────────────────────────────────", tone: "section" },
    { text: "" },
    { text: "Back-End Developer", tone: "accent indent" },
    { text: "BLDNG.ai AS · 04/2021–05/2025 · Oslo", tone: "indent" },
    { text: "fmr. Telenor Smarte Bygg", tone: "indent dim" },
    { text: "" },
    { text: "─────────────────────────────────────────", tone: "section" },
    { text: "" },
    { text: "Full Stack Developer", tone: "accent indent" },
    { text: "Telenor · 01/2021–04/2021 · Oslo", tone: "indent" },
    { text: "" },
    { text: "─────────────────────────────────────────", tone: "section" },
    { text: "" },
    { text: "Consultant – Full Stack Developer", tone: "accent indent" },
    { text: "Netlight · 03/2019–12/2020 · Oslo", tone: "indent" },
    { text: "" },
    { text: "─────────────────────────────────────────", tone: "section" },
    { text: "" },
    { text: "Full Stack Developer", tone: "accent indent" },
    { text: "Schjærven · 11/2017–02/2019 · Oslo", tone: "indent" },
    { text: "" },
    { text: "─────────────────────────────────────────", tone: "section" },
    { text: "" },
    { text: "Full Stack Developer", tone: "accent indent" },
    { text: "M7Dev · 12/2016–11/2017 · Bergen", tone: "indent" },
    { text: "" },
    { text: "→ 9 yrs · Type 'focus' for focus areas.", tone: "dim" },
  ],
});

