name: Build and Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Check dist folder size
      - name: Check dist folder size
        run: du -sh dist

      # Step 6: Upload the built folder as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # GitHub Pages expects this artifact name
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      # Step 1: Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
